mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('polls.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
                  path('', views.IndexView.as_view(), name='index'),
                  path('<int:pk>/', views.DetailView.as_view(), name='detail'),
                  path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
                  path('<int:pk>/image', views.ImageView.as_view(), name='image'),
                  path('<int:pk>/meme', views.MemView.as_view(), name='meme'),
                  path('<int:image_id>/set_text/', views.set_text, name='set_text'),
                  path('<int:mem_id>/download/', views.download, name='download'),
                  path('<int:question_id>/vote/', views.vote, name='vote'),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mysite/polls/models.py
import datetime
import textwrap

import PIL
from PIL import Image, ImageDraw, ImageFont
from django.db import models
from django.utils import timezone


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Image(models.Model):
    path = models.CharField(max_length=200)

    def __str__(self):
        return self.path


class Mem(models.Model):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    path = models.CharField(max_length=200)
    upper_text = models.CharField(max_length=200)
    lower_text = models.CharField(max_length=200)

    @staticmethod
    def generate_meme(image_path,
                      dst_path,
                      top_text,
                      bottom_text='',
                      font_path='',
                      font_size=9,
                      stroke_width=5):
        # load image
        im = PIL.Image.open(image_path)

        draw = ImageDraw.Draw(im)
        image_width, image_height = im.size

        # load font
        font = ImageFont.truetype(font=font_path, size=int(image_height * font_size) // 100)

        # convert text to uppercase
        top_text = top_text.upper()
        bottom_text = bottom_text.upper()

        # text wrapping
        char_width, char_height = font.getsize('A')
        chars_per_line = image_width // char_width
        top_lines = textwrap.wrap(top_text, width=chars_per_line)
        bottom_lines = textwrap.wrap(bottom_text, width=chars_per_line)

        # draw top lines
        y = 10
        for line in top_lines:
            line_width, line_height = font.getsize(line)
            x = (image_width - line_width) / 2
            draw.text((x, y), line, fill='white', font=font, stroke_width=stroke_width, stroke_fill='black')
            y += line_height

        # draw bottom lines
        y = image_height - char_height * len(bottom_lines) - 15
        for line in bottom_lines:
            line_width, line_height = font.getsize(line)
            x = (image_width - line_width) / 2
            draw.text((x, y), line, fill='white', font=font, stroke_width=stroke_width, stroke_fill='black')
            y += line_height

        # save meme
        im.save(dst_path)

    def __str__(self):
        return self.image

mysite/polls/views.py
import mimetypes
import os

from django.conf import settings
from django.http import HttpResponseRedirect, Http404, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Choice, Question, Mem, Image


def load_images():
    for file in os.listdir(settings.STATICFILES_DIRS[0] + settings.IMAGES_DIR):
        print("inserted " + file)
        try:
            Image.objects.get_or_create(path=settings.IMAGES_DIR + file)
            print("inserted " + file)
        except (KeyError, Image.DoesNotExist):
            print("already exists " + file)


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_images_list'

    load_images()

    def get_queryset(self):
        """Return 20 static images."""
        return Image.objects.all()


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


class ImageView(generic.DetailView):
    model = Image
    template_name = 'polls/image.html'


class MemView(generic.DetailView):
    model = Mem
    template_name = 'polls/mem.html'


def set_text(request, image_id):
    selected_image = get_object_or_404(Image, pk=image_id)
    try:
        print("new mem " + selected_image.path)
        upper_text = request.POST.get('utext')
        lower_text = request.POST.get('ltext')
        mem = Mem.objects.get_or_create(image=selected_image,
                                        upper_text=upper_text,
                                        lower_text=lower_text)[0]
        mem.path = settings.MEMES_DIR + str(mem.id) + '.jpg'
        mem.save()
        Mem.generate_meme(image_path=settings.STATICFILES_DIRS[0] + selected_image.path,
                          font_path=settings.STATICFILES_DIRS[0] + '/fonts/impact/impact.ttf',
                          dst_path=settings.STATICFILES_DIRS[0] + mem.path,
                          top_text=upper_text,
                          bottom_text=lower_text)
        return HttpResponseRedirect(reverse('polls:meme', args=(mem.id,)))
    except (KeyError, Mem.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/image.html', {
            'mem': image_id,
            'error_message': "You didn't select a text.",
        })


def download(request, mem_id):
    file_path = settings.STATICFILES_DIRS[0] + settings.MEMES_DIR + str(mem_id) + '.jpg'
    print('download ' + file_path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            mime_type, _ = mimetypes.guess_type(file_path)
            response = HttpResponse(fh.read(), content_type=mime_type)
            response['Content-Disposition'] = 'attachment; filename=' + os.path.basename(file_path)
            return response
    raise Http404


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/image.html
<h1>{{ image.path }}</h1>
{% load static %}
 <img src="{% static image.path %}" width="200px"/>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:set_text' image.id %}" method="post">
    {% csrf_token %}
    <label for="utext">Upper Text:</label>
    <input id="utext" name="utext" type="text"><br><br>
    <label for="ltext">Last name:</label>
    <input id="ltext" name="ltext" type="text"><br><br>
    <input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}
{% block content %}
<h1>Choose your image</h1>
{% for image in latest_images_list %}
<a href="{% url 'polls:image' image.id %}">
    <!--<a href="{{ file.id }}/image/">-->
    <img src="{% static image.path %}" width="200px"/>
</a>
{% endfor %}
{% endblock %}

mysite/polls/templates/polls/mem.html
<h1>{{ mem.path }}</h1>
{% load static %}
<img src="{% static mem.path %}" width="200px"/>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<input onclick="window.open('download')" type="button" value="Download">

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>